AWSTemplateFormatVersion: "2010-09-09"
Description: The Product Certificate Authority Stack
Parameters:
  CreationDate:
    Description: Date
    Type: String
    Default: '2019-02-05 08:00:00'
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
Resources:
  CRLBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain # RETAIN when you delete the CF stack
    Properties:
      BucketName: theproduct-ca-crl-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "Name"
          Value: "theproduct-ca-crl-bucket" #Enter your bucket name here
        -
          Key: "Description"
          Value: "S3 Bucket for CA CRL" #Enter your description here
  CRLBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CRLBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: acm-pca.amazonaws.com
          Action:
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:GetBucketAcl
          - s3:GetBucketLocation
          Resource:
            - !Sub arn:aws:s3:::${CRLBucket}/*
            - !Sub arn:aws:s3:::${CRLBucket}
  PrivateCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      Type: ROOT
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        Country: US
        State: California
        Locality: La Jolla
        Organization: The Product
        OrganizationalUnit: Information Technology
        CommonName: theproduct.internal
      RevocationConfiguration:
        CrlConfiguration:
          Enabled: true
          ExpirationInDays: 7
          S3BucketName: !Ref CRLBucket
  RootCert:
    Type: AWS::ACMPCA::Certificate
    Properties:
      CertificateAuthorityArn: !Ref PrivateCA
      CertificateSigningRequest: !GetAtt
        - PrivateCA
        - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      TemplateArn: 'arn:aws:acm-pca:::template/RootCACertificate/V1'
      Validity:
        Type: YEARS
        Value: 10
  PrivateCAActivation:
    Type: 'AWS::ACMPCA::CertificateAuthorityActivation'
    Properties:
      CertificateAuthorityArn: !Ref PrivateCA
      Certificate: !GetAtt 
        - RootCert
        - Certificate
      Status: ACTIVE