AWSTemplateFormatVersion: "2010-09-09"
Description: The Product Client VPN Stack
Parameters:
  CreationDate:
    Description: Date
    Type: String
    Default: '2019-02-05 08:00:00'
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
Resources:
  ClientVPNSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue vpc-vpcid
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: TheProduct-ClientVPNSubnet
  myClientVpnEndpoint:
    Type: AWS::EC2::ClientVpnEndpoint
    Properties:
      Description: "My Client VPN Endpoint"
      AuthenticationOptions:
        - Type: "directory-service-authentication"
          ActiveDirectory:
              DirectoryId: !ImportValue myDirectory
      ClientCidrBlock: 10.0.248.0/22
      ConnectionLogOptions:
        Enabled: false
      DnsServers:
        - !ImportValue myDirectoryDNS1
        - !ImportValue myDirectoryDNS2
      # ServerCertificateArn: !ImportValue RootCert
      ServerCertificateArn: arn:aws:acm:us-west-2:648971150110:certificate/29fe637f-6004-4969-95d2-7d0b697c6233
      TagSpecifications:
        - ResourceType: "client-vpn-endpoint"
          Tags:
          - Key: "Name"
            Value: "theproduct-clientvpn"
      TransportProtocol: "udp"
      SplitTunnel: true
