AWSTemplateFormatVersion: "2010-09-09"
Description: The Product Security Stack
Parameters:
  CreationDate:
    Description: Date
    Type: String
    Default: '2019-02-05 08:00:00'
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
Resources:
  S3CloudTrail:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain # RETAIN when you delete the CF stack
    Properties:
      BucketName: theproduct-cloudtrail
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "Name"
          Value: "theproduct-cloudtrail" #Enter your bucket name here
        -
          Key: "Description"
          Value: "S3 Bucket for CloudTrail" #Enter your description here
  S3CloudTrailPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3CloudTrail
      PolicyDocument:
        Statement:
        - Sid: Stmt1533652298100
          Action: s3:*
          Effect: Deny
          Resource:
            !Sub |-
              arn:aws:s3:::${S3CloudTrail}
          Condition:
            Bool:
              aws:SecureTransport: 'false'
          Principal: "*"
        - Sid: "AWSCloudTrailAclCheck"
          Effect: "Allow"
          Principal: 
            Service: "cloudtrail.amazonaws.com"
          Action: "s3:GetBucketAcl"
          Resource: 
            !Sub |-
              arn:aws:s3:::${S3CloudTrail}
        - Sid: "AWSCloudTrailWrite"
          Effect: "Allow"
          Principal: 
            Service: "cloudtrail.amazonaws.com"
          Action: "s3:PutObject"
          Resource:
            !Sub |-
              arn:aws:s3:::${S3CloudTrail}/AWSLogs/${AWS::AccountId}/*
          Condition: 
            StringEquals:
              s3:x-amz-acl: "bucket-owner-full-control"
  myVPCCloudWatch:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: cloudtrail-mgmt-logs
      RetentionInDays: 180
  CloudTrailCloudWatchLogsRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CloudTrail_CloudWatchLogs_Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "vpc-flow-logs.amazonaws.com"
                - "cloudtrail.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "cloudtrail-mgmt-logs-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AWSCloudTrailCreateLogStream
              Effect: Allow
              Action:
              - logs:CreateLogStream
              Resource:
                !Sub |-
                  arn:aws:logs:us-west-2:${AWS::AccountId}:log-group:cloudtrail-mgmt-logs:log-stream:${AWS::AccountId}_CloudTrail_us-west-2*
            - Sid: AWSCloudTrailPutLogEvents
              Effect: Allow
              Action:
              - logs:PutLogEvents
              Resource:
                !Sub |-
                  arn:aws:logs:us-west-2:${AWS::AccountId}:log-group:cloudtrail-mgmt-logs:log-stream:${AWS::AccountId}_CloudTrail_us-west-2*
        - 
          PolicyName: CloudTrail_CloudWatchLogs_Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              Effect: Allow
              Resource: "*"
  myTrail: 
    DependsOn: 
      - S3CloudTrailPolicy
      - SNSPolicy
    Type: AWS::CloudTrail::Trail
    Properties: 
      S3BucketName: 
        Ref: S3CloudTrail
      SnsTopicName: 
        Fn::GetAtt: 
          - CloudTrailSNS
          - TopicName
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      TrailName: mgmt-cloudtrail
      KMSKeyId: alias/s3-mgmt-cloudtrail-kms
      EnableLogFileValidation: true
      CloudWatchLogsLogGroupArn: 
        !Sub |-
          arn:aws:logs:us-west-2:${AWS::AccountId}:log-group:cloudtrail-mgmt-logs:*
      CloudWatchLogsRoleArn: 
        !Sub |-
          arn:aws:iam::${AWS::AccountId}:role/CloudTrail_CloudWatchLogs_Role
      EventSelectors:
        - DataResources:
          - Type: AWS::S3::Object
            Values:
                - 'arn:aws:s3'
        - ReadWriteType: All
  CloudTrailSNS:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: sns-mgmt-cloudtrail
  SNSPolicy: 
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - Ref: "CloudTrailSNS"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
            Resource: 
              !Sub |-
                ${CloudTrailSNS}
            Condition:
              StringEquals:
                AWS:SourceOwner: 
                  !Sub |-
                    '${AWS::AccountId}'
          - Sid: "AWSCloudTrailSNSPolicy"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Resource: 
              !Sub |-
                ${CloudTrailSNS}
            Action: "SNS:Publish"
  ConfigRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ConfigRole
        Path: "/"
        AssumeRolePolicyDocument: 
          Version: '2012-10-17'
          Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
        Policies:
          - 
            PolicyName: "root"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - s3:PutObject
                Resource:
                  !Sub |-
                    arn:aws:s3:::${S3CloudTrail}/AWSLogs/${AWS::AccountId}/*
                Condition:
                  StringLike:
                    s3:x-amz-acl: bucket-owner-full-control
              - Effect: Allow
                Action:
                - s3:GetBucketAcl
                Resource: 
                  !Sub |-
                    arn:aws:s3:::${S3CloudTrail}
  ConfigDelivery:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName: !Ref S3CloudTrail
Outputs:
  CloudTrailRoleOutput:
    Description: CloudTrail CloudWatch Logs Role
    Value: !Ref CloudTrailCloudWatchLogsRole
    Export:
      Name: cloudtrail-role