AWSTemplateFormatVersion: "2010-09-09"
Description: The Product VPC Stack
Parameters:
  CreationDate:
    Description: Date
    Type: String
    Default: '2019-02-05 08:00:00'
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: TheProduct-VPC
  PubSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: TheProduct-Public-2A
  PubSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: TheProduct-Public-2B
  PrivSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: TheProduct-Private-2A
  PrivSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: TheProduct-Private-2B
  myInetGw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: TheProduct-InetGw
  myInetGwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: 
        Ref: myInetGw
      VpcId: 
        Ref: myVPC
  NatGw2AEIP:
    DependsOn: myInetGwAttach
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGw2A:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
        - NatGw2AEIP
        - AllocationId
      SubnetId:
        Ref: PrivSubnet2A
      Tags:
      - Key: Name
        Value: TheProduct-NatGateway-2A
