AWSTemplateFormatVersion: "2010-09-09"
Description: Skylab VPC Stack
Parameters:
  CreationDate:
    Description: Date
    Type: String
    Default: '2019-02-05 08:00:00'
    AllowedPattern: "^\\d{4}(-\\d{2}){2} (\\d{2}:){2}\\d{2}$"
    ConstraintDescription: Date and time of creation
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: Skylab-VPC
  PubSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: Skylab-Public-2A
  PubSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: Skylab-Public-2B
  PrivSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: Skylab-Private-2A
  PrivSubnet2B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: Skylab-Private-2B
  myInetGw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Skylab-InetGw
  myInetGwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: 
        Ref: myInetGw
      VpcId: 
        Ref: myVPC
  NatGw2AEIP:
    DependsOn: myInetGwAttach
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NatGw2BEIP:
    DependsOn: myInetGwAttach
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGw2A:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
        - NatGw2AEIP
        - AllocationId
      SubnetId:
        Ref: PubSubnet2A
      Tags:
      - Key: Name
        Value: Skylab-NatGateway-2A
  NATGw2B:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: 
        Fn::GetAtt:
        - NatGw2BEIP
        - AllocationId
      SubnetId:
        Ref: PubSubnet2B
      Tags:
      - Key: Name
        Value: Skylab-NatGateway-2B
  RouteTablePriv2A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Skylab-routetable-private2a
  RouteNatGW2A:
    Type: AWS::EC2::Route
    DependsOn: myInetGw
    Properties: 
      RouteTableId:
        Ref: RouteTablePriv2A
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATGw2A
  RouteTablePriv2AAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePriv2A
      SubnetId: 
        Ref: PrivSubnet2A
  RouteTablePriv2B:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Skylab-routetable-private2b
  RouteNatGW2B:
    Type: AWS::EC2::Route
    DependsOn: myInetGw
    Properties: 
      RouteTableId:
        Ref: RouteTablePriv2B
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATGw2B
  RouteTablePriv2BAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePriv2B
      SubnetId: 
        Ref: PrivSubnet2B
  RouteTablePub2A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Skylab-routetable-public2a
  RouteInetGw2A:
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId:
        Ref: RouteTablePub2A
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInetGw
  RouteTablePub2AAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePub2A
      SubnetId: 
        Ref: PubSubnet2A
  RouteTablePub2b:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Skylab-routetable-public2b
  RouteInetGw2b:
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId:
        Ref: RouteTablePub2b
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInetGw
  RouteTablePub2bAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePub2b
      SubnetId: 
        Ref: PubSubnet2B
  myFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: 
        !Sub |-
          arn:aws:iam::${AWS::AccountId}:role/CloudTrail_CloudWatchLogs_Role
      ResourceId: !Ref myVPC
      ResourceType: VPC
      TrafficType: ALL
      LogGroupName: cloudtrail-mgmt-logs
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private Subnets
      DBSubnetGroupName: private-subnets
      SubnetIds:
        - !Ref PrivSubnet2A
        - !Ref PrivSubnet2B
Outputs:
  vpcidoutput:
    Description: Resource ID of VPC
    Value:
      Ref: myVPC
    Export:
      Name: vpc-vpcid
  pubsubnet2aoutput:
    Description: Resource ID of the Public Subnet 2a
    Value:
      Ref: PubSubnet2A
    Export:
      Name: vpc-pubsubnet2a-id
  pubsubnet2boutput:
    Description: Resource ID of the Public Subnet 2b
    Value:
      Ref: PubSubnet2B
    Export:
      Name: vpc-pubsubnet2b-id
  privsubnet2aoutput:
    Description: Resource ID of the Private Subnet 2a
    Value:
      Ref: PrivSubnet2A
    Export:
      Name: vpc-privsubnet2a-id
  privsubnet2boutput:
    Description: Resource ID of the Private Subnet 2b
    Value:
      Ref: PrivSubnet2B
    Export:
      Name: vpc-privsubnet2b-id